/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IComptroller, IComptrollerInterface } from "../IComptroller";

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_buyers",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "_investmentAmounts",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "_minSharesQuantities",
        type: "uint256[]",
      },
    ],
    name: "buyShares",
    outputs: [
      {
        internalType: "uint256[]",
        name: "sharesReceivedAmounts_",
        type: "uint256[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "redeemShares",
    outputs: [
      {
        internalType: "address[]",
        name: "payoutAssets_",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "payoutAmounts_",
        type: "uint256[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_sharesQuantity",
        type: "uint256",
      },
      {
        internalType: "address[]",
        name: "_additionalAssets",
        type: "address[]",
      },
      {
        internalType: "address[]",
        name: "_assetsToSkip",
        type: "address[]",
      },
    ],
    name: "redeemSharesDetailed",
    outputs: [
      {
        internalType: "address[]",
        name: "payoutAssets_",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "payoutAmounts_",
        type: "uint256[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IComptroller__factory {
  static readonly abi = _abi;
  static createInterface(): IComptrollerInterface {
    return new utils.Interface(_abi) as IComptrollerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IComptroller {
    return new Contract(address, _abi, signerOrProvider) as IComptroller;
  }
}
